services:
  gomall-cart:
    image: 'gomall-cart:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/cart/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network

networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
