services:
  gomall-prodect:
    image: 'gomall-prodect:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/prodect/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network
networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
