services:

  gomall-frontend:
    image: 'gomall-frontend:latest'
    ports:
      - 8081:8081
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/frontend/conf:ro
      - ./static:/opt/gomall/frontend/static:ro
      - ./templates:/opt/gomall/frontend/templates:ro
    networks:
      - go-tiktok_e-commence_gomall-network

networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
     