// Code generated by Kitex v0.9.1. DO NOT EDIT.

package productcatalogservice

import (
	"context"
	product "e-commence/rpc_gen/kitex_gen/product"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListProduct": kitex.NewMethodInfo(
		listProductHandler,
		newListProductArgs,
		newListProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetProduct": kitex.NewMethodInfo(
		getProductHandler,
		newGetProductArgs,
		newGetProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SerachProduct": kitex.NewMethodInfo(
		serachProductHandler,
		newSerachProductArgs,
		newSerachProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	productCataLogServiceServiceInfo                = NewServiceInfo()
	productCataLogServiceServiceInfoForClient       = NewServiceInfoForClient()
	productCataLogServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productCataLogServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productCataLogServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productCataLogServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductCataLogService"
	handlerType := (*product.ProductCataLogService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func listProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.ListProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCataLogService).ListProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListProductArgs:
		success, err := handler.(product.ProductCataLogService).ListProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListProductArgs() interface{} {
	return &ListProductArgs{}
}

func newListProductResult() interface{} {
	return &ListProductResult{}
}

type ListProductArgs struct {
	Req *product.ListProductReq
}

func (p *ListProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.ListProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListProductArgs) Unmarshal(in []byte) error {
	msg := new(product.ListProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListProductArgs_Req_DEFAULT *product.ListProductReq

func (p *ListProductArgs) GetReq() *product.ListProductReq {
	if !p.IsSetReq() {
		return ListProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListProductResult struct {
	Success *product.ListProductResp
}

var ListProductResult_Success_DEFAULT *product.ListProductResp

func (p *ListProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.ListProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListProductResult) Unmarshal(in []byte) error {
	msg := new(product.ListProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListProductResult) GetSuccess() *product.ListProductResp {
	if !p.IsSetSuccess() {
		return ListProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.ListProductResp)
}

func (p *ListProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListProductResult) GetResult() interface{} {
	return p.Success
}

func getProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.GetProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCataLogService).GetProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetProductArgs:
		success, err := handler.(product.ProductCataLogService).GetProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetProductArgs() interface{} {
	return &GetProductArgs{}
}

func newGetProductResult() interface{} {
	return &GetProductResult{}
}

type GetProductArgs struct {
	Req *product.GetProductReq
}

func (p *GetProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.GetProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetProductArgs) Unmarshal(in []byte) error {
	msg := new(product.GetProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetProductArgs_Req_DEFAULT *product.GetProductReq

func (p *GetProductArgs) GetReq() *product.GetProductReq {
	if !p.IsSetReq() {
		return GetProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetProductResult struct {
	Success *product.GetProductResp
}

var GetProductResult_Success_DEFAULT *product.GetProductResp

func (p *GetProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.GetProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetProductResult) Unmarshal(in []byte) error {
	msg := new(product.GetProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetProductResult) GetSuccess() *product.GetProductResp {
	if !p.IsSetSuccess() {
		return GetProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.GetProductResp)
}

func (p *GetProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetProductResult) GetResult() interface{} {
	return p.Success
}

func serachProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.SearchProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCataLogService).SerachProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SerachProductArgs:
		success, err := handler.(product.ProductCataLogService).SerachProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SerachProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSerachProductArgs() interface{} {
	return &SerachProductArgs{}
}

func newSerachProductResult() interface{} {
	return &SerachProductResult{}
}

type SerachProductArgs struct {
	Req *product.SearchProductReq
}

func (p *SerachProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.SearchProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SerachProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SerachProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SerachProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SerachProductArgs) Unmarshal(in []byte) error {
	msg := new(product.SearchProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SerachProductArgs_Req_DEFAULT *product.SearchProductReq

func (p *SerachProductArgs) GetReq() *product.SearchProductReq {
	if !p.IsSetReq() {
		return SerachProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SerachProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SerachProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SerachProductResult struct {
	Success *product.SearchProductResp
}

var SerachProductResult_Success_DEFAULT *product.SearchProductResp

func (p *SerachProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.SearchProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SerachProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SerachProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SerachProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SerachProductResult) Unmarshal(in []byte) error {
	msg := new(product.SearchProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SerachProductResult) GetSuccess() *product.SearchProductResp {
	if !p.IsSetSuccess() {
		return SerachProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SerachProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.SearchProductResp)
}

func (p *SerachProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SerachProductResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListProduct(ctx context.Context, Req *product.ListProductReq) (r *product.ListProductResp, err error) {
	var _args ListProductArgs
	_args.Req = Req
	var _result ListProductResult
	if err = p.c.Call(ctx, "ListProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProduct(ctx context.Context, Req *product.GetProductReq) (r *product.GetProductResp, err error) {
	var _args GetProductArgs
	_args.Req = Req
	var _result GetProductResult
	if err = p.c.Call(ctx, "GetProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SerachProduct(ctx context.Context, Req *product.SearchProductReq) (r *product.SearchProductResp, err error) {
	var _args SerachProductArgs
	_args.Req = Req
	var _result SerachProductResult
	if err = p.c.Call(ctx, "SerachProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
