services:
  gomall-email:
    image: 'gomall-email:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/email/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network

networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
