services:
  gomall-checkout:
    image: 'gomall-checkout:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/checkout/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network

networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
