// Code generated by Kitex v0.9.1. DO NOT EDIT.

package userservice

import (
	"context"
	user "e-commence/gomall/kitex_gen/user"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UserCreate": kitex.NewMethodInfo(
		userCreateHandler,
		newUserCreateArgs,
		newUserCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func userCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.UserCreateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserService).UserCreate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserCreateArgs:
		success, err := handler.(user.UserService).UserCreate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserCreateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserCreateArgs() interface{} {
	return &UserCreateArgs{}
}

func newUserCreateResult() interface{} {
	return &UserCreateResult{}
}

type UserCreateArgs struct {
	Req *user.UserCreateReq
}

func (p *UserCreateArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.UserCreateReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UserCreateArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UserCreateArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UserCreateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserCreateArgs) Unmarshal(in []byte) error {
	msg := new(user.UserCreateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserCreateArgs_Req_DEFAULT *user.UserCreateReq

func (p *UserCreateArgs) GetReq() *user.UserCreateReq {
	if !p.IsSetReq() {
		return UserCreateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserCreateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserCreateResult struct {
	Success *user.UserCreateResp
}

var UserCreateResult_Success_DEFAULT *user.UserCreateResp

func (p *UserCreateResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.UserCreateResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UserCreateResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UserCreateResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UserCreateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserCreateResult) Unmarshal(in []byte) error {
	msg := new(user.UserCreateResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserCreateResult) GetSuccess() *user.UserCreateResp {
	if !p.IsSetSuccess() {
		return UserCreateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UserCreateResp)
}

func (p *UserCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserCreateResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserCreate(ctx context.Context, Req *user.UserCreateReq) (r *user.UserCreateResp, err error) {
	var _args UserCreateArgs
	_args.Req = Req
	var _result UserCreateResult
	if err = p.c.Call(ctx, "UserCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
