services:
  gomall-product:
    image: 'gomall-product:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/product/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network
networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
