services:
  mysql:
    image: 'mysql:latest'
    ports:
      - ${GOMALL_MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${GOMALL_MYSQL_DATABASE}
      - MYSQL_USER=${GOMALL_MYSQL_USER}
      - MYSQL_PASSWORD=${GOMALL_MYSQL_PASSWORD}
      # - MYSQL_RANDOM_ROOT_PASSWORD= "yes"
      - MYSQL_ROOT_PASSWORD={GOMALL_MYSQL_DATABASE}
  redis:
    image: 'redis:latest'
    ports:
      - ${GOMALL_REDIS_PORT}:6379
  consul:
    image: 'hashicorp/consul'
    ports:
      - ${GOMALL_CONSUL_PORT}:8500