services:

  gomall-user:
    image: 'gomall-user:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/user/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network

networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
