services:
  gomall-order:
    image: 'gomall-order:latest'
    env_file:
      - .env
    volumes:  
      - ./conf:/opt/gomall/order/conf:ro
    networks:
      - go-tiktok_e-commence_gomall-network

networks:
  go-tiktok_e-commence_gomall-network:                
      external: true
